(function(){if(sessionStorage.fontsLoadedFoftPolyfill)document.documentElement.className+=" fonts-loaded-1 fonts-loaded-2";else{(function(){function q(b){g.push(b);1==g.length&&B()}function n(){for(;g.length;)g[0](),g.shift()}function f(b){this.a=h;this.b=void 0;this.f=[];var c=this;try{b(function(a){x(c,a)},function(a){k(c,a)})}catch(a){k(c,a)}}function w(b){return new f(function(c,a){a(b)})}function l(b){return new f(function(c){c(b)})}function x(b,c){if(b.a==h){if(c==b)throw new TypeError;var a=
!1;try{var e=c&&c.then;if(null!=c&&"object"==typeof c&&"function"==typeof e){e.call(c,function(d){a||x(b,d);a=!0},function(d){a||k(b,d);a=!0});return}}catch(d){a||k(b,d);return}b.a=0;b.b=c;p(b)}}function k(b,c){if(b.a==h){if(c==b)throw new TypeError;b.a=1;b.b=c;p(b)}}function p(b){q(function(){if(b.a!=h)for(;b.f.length;){var c=b.f.shift(),a=c[0],e=c[1],d=c[2];c=c[3];try{0==b.a?"function"==typeof a?d(a.call(void 0,b.b)):d(b.b):1==b.a&&("function"==typeof e?d(e.call(void 0,b.b)):c(b.b))}catch(C){c(C)}}})}
function r(b){return new f(function(c,a){function e(a){return function(e){f[a]=e;d+=1;d==b.length&&c(f)}}var d=0,f=[];0==b.length&&c(f);for(var g=0;g<b.length;g+=1)l(b[g]).c(e(g),a)})}function D(b){return new f(function(c,a){for(var e=0;e<b.length;e+=1)l(b[e]).c(c,a)})}var g=[];var B=function(){setTimeout(n)};var h=2;f.prototype.g=function(b){return this.c(void 0,b)};f.prototype.c=function(b,c){var a=this;return new f(function(e,d){a.f.push([b,c,e,d]);p(a)})};window.Promise||(window.Promise=f,window.Promise.resolve=
l,window.Promise.reject=w,window.Promise.race=D,window.Promise.all=r,window.Promise.prototype.then=f.prototype.c,window.Promise.prototype["catch"]=f.prototype.g)})();(function(){function q(a,b){document.addEventListener?a.addEventListener("scroll",b,!1):a.attachEvent("scroll",b)}function n(a){document.body?a():document.addEventListener?document.addEventListener("DOMContentLoaded",function d(){document.removeEventListener("DOMContentLoaded",d);a()}):document.attachEvent("onreadystatechange",function C(){if("interactive"==
document.readyState||"complete"==document.readyState)document.detachEvent("onreadystatechange",C),a()})}function f(a){this.a=document.createElement("div");this.a.setAttribute("aria-hidden","true");this.a.appendChild(document.createTextNode(a));this.b=document.createElement("span");this.c=document.createElement("span");this.h=document.createElement("span");this.f=document.createElement("span");this.g=-1;this.b.style.cssText="max-width:none;display:inline-block;position:absolute;height:100%;width:100%;overflow:scroll;font-size:16px;";
this.c.style.cssText="max-width:none;display:inline-block;position:absolute;height:100%;width:100%;overflow:scroll;font-size:16px;";this.f.style.cssText="max-width:none;display:inline-block;position:absolute;height:100%;width:100%;overflow:scroll;font-size:16px;";this.h.style.cssText="display:inline-block;width:200%;height:200%;font-size:16px;max-width:none;";this.b.appendChild(this.h);this.c.appendChild(this.f);this.a.appendChild(this.b);this.a.appendChild(this.c)}function w(a,b){a.a.style.cssText=
"max-width:none;min-width:20px;min-height:20px;display:inline-block;overflow:hidden;position:absolute;width:auto;margin:0;padding:0;top:-999px;white-space:nowrap;font-synthesis:none;font:"+b+";"}function l(a){var b=a.a.offsetWidth,d=b+100;a.f.style.width=d+"px";a.c.scrollLeft=d;a.b.scrollLeft=a.b.scrollWidth+100;return a.g!==b?(a.g=b,!0):!1}function x(a,b){function d(){var a=c;l(a)&&a.a.parentNode&&b(a.g)}var c=a;q(a.b,d);q(a.c,d);l(a)}function k(a,b){b=b||{};this.family=a;this.style=b.style||"normal";
this.weight=b.weight||"normal";this.stretch=b.stretch||"normal"}function p(){if(null===h)if(r()&&/Apple/.test(window.navigator.vendor)){var a=/AppleWebKit\/([0-9]+)(?:\.([0-9]+))(?:\.([0-9]+))/.exec(window.navigator.userAgent);h=!!a&&603>parseInt(a[1],10)}else h=!1;return h}function r(){null===c&&(c=!!document.fonts);return c}function D(){if(null===b){var a=document.createElement("div");try{a.style.font="condensed 100px sans-serif"}catch(e){}b=""!==a.style.font}return b}function g(a,b){return[a.style,
a.weight,D()?a.stretch:"","100px",b].join(" ")}var B=null,h=null,b=null,c=null;k.prototype.load=function(b,c){var a=this,e=b||"BESbswy",h=0,k=c||3E3,q=(new Date).getTime();return new Promise(function(b,c){if(r()&&!p()){var d=new Promise(function(b,c){function d(){(new Date).getTime()-q>=k?c():document.fonts.load(g(a,'"'+a.family+'"'),e).then(function(a){1<=a.length?b():setTimeout(d,25)},function(){c()})}d()}),l=new Promise(function(a,b){h=setTimeout(b,k)});Promise.race([l,d]).then(function(){clearTimeout(h);
b(a)},function(){c(a)})}else n(function(){function d(){var c;if(c=-1!=t&&-1!=u||-1!=t&&-1!=v||-1!=u&&-1!=v)(c=t!=u&&t!=v&&u!=v)||(null===B&&(c=/AppleWebKit\/([0-9]+)(?:\.([0-9]+))/.exec(window.navigator.userAgent),B=!!c&&(536>parseInt(c[1],10)||536===parseInt(c[1],10)&&11>=parseInt(c[2],10))),c=B&&(t==n&&u==n&&v==n||t==p&&u==p&&v==p||t==r&&u==r&&v==r)),c=!c;c&&(m.parentNode&&m.parentNode.removeChild(m),clearTimeout(h),b(a))}function l(){if((new Date).getTime()-q>=k)m.parentNode&&m.parentNode.removeChild(m),
c(a);else{var b=document.hidden;if(!0===b||void 0===b)t=y.a.offsetWidth,u=z.a.offsetWidth,v=A.a.offsetWidth,d();h=setTimeout(l,50)}}var y=new f(e),z=new f(e),A=new f(e),t=-1,u=-1,v=-1,n=-1,p=-1,r=-1,m=document.createElement("div");m.dir="ltr";w(y,g(a,"sans-serif"));w(z,g(a,"serif"));w(A,g(a,"monospace"));m.appendChild(y.a);m.appendChild(z.a);m.appendChild(A.a);document.body.appendChild(m);n=y.a.offsetWidth;p=z.a.offsetWidth;r=A.a.offsetWidth;l();x(y,function(a){t=a;d()});w(y,g(a,'"'+a.family+'",sans-serif'));
x(z,function(a){u=a;d()});w(z,g(a,'"'+a.family+'",serif'));x(A,function(a){v=a;d()});w(A,g(a,'"'+a.family+'",monospace'))})})};"object"===typeof module?module.exports=k:(window.FontFaceObserver=k,window.FontFaceObserver.prototype.load=k.prototype.load)})();var E=new FontFaceObserver("LatoRegular");Promise.all([E.load(null,1E4)]).then(function(){document.documentElement.className+=" fonts-loaded-1";var q=new FontFaceObserver("Lato",{weight:400}),n=new FontFaceObserver("Lato",{weight:700}),f=new FontFaceObserver("Lato",
{weight:900});Promise.all([q.load(null,1E4),n.load(null,1E4),f.load(null,1E4)]).then(function(){document.documentElement.className+=" fonts-loaded-2";sessionStorage.fontsLoadedFoftPolyfill=!0})})}})();
