function LearningObjectiveList(h){window[h]=this;var a=this,e,g;a.text=null;a.learningObjectives=null;a.insertRequestProcessed=!1;a.toggeled=!1;a.editMode=ko.observable(!1);a.isAssessmentReportLinkVisible=ko.observable(!1);a.isAddLoButtonVisible=ko.observable(!1);a.canDelete=ko.observable(!1);a.saveChangesImmediately=ko.observable(!1);a.getLoCountAsString=function(){var b=a.getLearningObjectiveCount();return 0===b?a.settings.text.noLearningObjectives:1===b?String.format(a.settings.text.oneLearningObjective,
1):String.format(a.settings.text.severalLearningObjectives,b)};a.showMoreClick=function(a){a.expanded(!a.expanded())};a.toggleDescription=function(a){e.learningObjectives.forEach(function(b){b.descriptionIsShown(b==a?!b.descriptionIsShown():!1)})};a.deleteClick=function(b){a.saveChangesImmediately()?a.deleteLearningObjectiveImmediately(b):a.deleteLearningObjective(b,null,!1)};a.initialize=function(){e=a.settings;g=a.controls;a.text=e.text;a.applySettings(e);a.saveChangesImmediately(a.settings.saveChangesImmediately);
e.learningObjectives.forEach(function(b){a.extendListItem(b)});a.learningObjectives=ko.observableArray(e.learningObjectives);$(function(){ko.cleanNode($(g.container)[0]);ko.applyBindings(a,$(g.container)[0])})};a.applySettings=function(b){a.editMode(b.editMode);a.isAssessmentReportLinkVisible(b.isAssessmentReportLinkVisible);a.isAddLoButtonVisible(b.isAddLoButtonVisible);a.canDelete(a.settings.allowDelete&&a.editMode())};a.extendListItem=function(b){b.expanded=ko.observable(!0);b.showMoreLinkVisible=
ko.observable(!1);b.descriptionIsShown=ko.observable(!1);b.showMoreText=ko.pureComputed(function(){return this.expanded()?a.settings.text.showLess:a.settings.text.showMore},b);b.DeleteTitle=String.format(a.settings.text.deleteX,b.Title);return b};a.extendListItems=function(b){b.forEach(function(b){a.extendListItem(b)});return b};a.toggleItems=function(){a.toggeled||(ko.utils.arrayForEach(a.learningObjectives(),function(b){a.toggleItem(b)}),a.toggeled=!0)};a.toggleItem=function(b){var c=$("[item-id="+
b.Id+"]");c.height()>parseFloat(c.css("line-height"))*a.settings.maximumNumberOfLinesToShowForDescription&&(b.showMoreLinkVisible(!0),b.expanded(!1))};a.setOptionSaveChangesImmediately=function(b){a.saveChangesImmediately(b)};a.closeContextDialog=function(){$(".ccl-context-dialog-close").click()};a.insertLearningObjectives=function(b){var c=[];b.forEach(function(a){c.push(parseInt(a))});setTimeout(function(){a.insertRequestProcessed||window[a.settings.learningObjectivesSelectorClientInstanceName].showProgressFeedback()},
1E3);b=a.getInsertedLearningObjectives(c);a.saveChangesImmediately()?a.addNewLearningObjectivesImmediately(b):a.addNewLearningObjectives(b)};a.openSelectorDialog=function(){var b=window[a.settings.learningObjectivesSelectorClientInstanceName];b.selectedIds=a.getLearningObjectiveIds();b.openDialog()};a.getInsertedLearningObjectives=function(b){var c=a.getLearningObjectiveIds();return b.filter(function(a){return 0>c.indexOf(a)})};a.getLearningObjectiveIds=function(){var b=[];ko.utils.arrayForEach(a.learningObjectives(),
function(a){b.push(a.Id)});return b};a.getLearningObjectives=function(){var b=[];ko.utils.arrayForEach(a.learningObjectives(),function(a){b.push(a)});return b};a.restoreLearningObjectives=function(b){a.needRestoreLearningObjectives(b)&&(a.learningObjectives.removeAll(),ko.utils.arrayPushAll(a.learningObjectives,b),a.setSelectedLearningObjectives())};a.needRestoreLearningObjectives=function(b){var c=a.learningObjectives(),d=!0;if(b.length!==c.length)return!0;for(var f=0;f<b.length;f++)if(b[f].Id!==
c[f].Id){d=!1;break}return!d};a.toggleNewAddedItems=function(b){var c=a.getLearningObjectiveCount();for(b=c-b;b<c;b++)a.toggleItem(a.learningObjectives()[b]);a.toggeled=!0};a.setSelectedLearningObjectives=function(){var b=[];a.getLearningObjectiveIds().forEach(function(a){b.push(a.toString())});window[a.settings.learningObjectivesSelectorClientInstanceName].setSelectedIds(b,!0)};a.getLearningObjectiveCount=function(){return a.learningObjectives().length};a.addNewLearningObjectivesImmediately=function(b){$.ajax({type:"POST",
url:a.settings.addLearningObjectivesToElementServiceUrl,data:$.param({elementId:a.settings.elementId,courseId:a.settings.courseId,learningObjectiveIds:b,returnUrl:a.settings.returnUrl},!0),dataType:"json",success:function(b){a.finishAddingLearningObjectives(b.learningObjectives,b.maxScore,!1)},error:function(a){CCL.CommonFunctions.alertAjaxError(a)}})};a.addNewLearningObjectives=function(b,c){CCL.CommonFunctions.safeAjaxPost({url:a.settings.getLearningObjectivesServiceUrl.replace("{elementId}",a.settings.elementId),
data:{courseId:a.settings.courseId,learningObjectiveIds:b,returnUrl:a.settings.returnUrl}}).done(function(b){a.finishAddingLearningObjectives(b.learningObjectives,null,c)}).fail(function(a){CCL.CommonFunctions.alertAjaxError(a)})};a.finishAddingLearningObjectives=function(b,c,d){ko.utils.arrayPushAll(a.learningObjectives,a.extendListItems(b));a.toggeled=!1;a.insertRequestProcessed=!0;$(document).trigger(a.settings.eventSelectionSavedJsName);$(document).trigger(a.settings.eventListChangeName,{ids:a.getLearningObjectiveIds(),
maxScore:c,isSyncContext:d});window[a.settings.learningObjectivesSelectorClientInstanceName].showSuccessFeedback();a.setSelectedLearningObjectives()};a.deleteLearningObjectiveImmediately=function(b){$.ajax({type:"POST",url:a.settings.deleteLearningObjectivesFromElementServiceUrl,data:$.param({elementId:a.settings.elementId,courseId:a.settings.courseId,learningObjectiveIds:[b.Id]},!0),dataType:"json",success:function(c){a.deleteLearningObjective(b,c.maxScore,!1)},error:function(a){CCL.CommonFunctions.alertAjaxError(a)}})};
a.deleteLearningObjective=function(b,c,d){a.learningObjectives.remove(b);$(document).trigger(a.settings.eventListChangeName,{ids:a.getLearningObjectiveIds(),maxScore:c,isSyncContext:d});a.setSelectedLearningObjectives()};a.syncLearningObjectives=function(b){var c=[];c=c.concat(b);var d=[];d=d.concat(a.learningObjectives());b&&0!==b.length?(d.forEach(function(d){b.includes(d.Id)?c.splice(c.indexOf(d.Id),1):a.deleteLearningObjective(d,null,!0)}),0<c.length&&a.addNewLearningObjectives(c,!0)):d.forEach(function(b){a.deleteLearningObjective(b,
null,!0)})};return a};
